packages:
  - apps/*
  - packages/*
  - packages/messaging/*
  - packages/messaging/providers/*
allowBuilds:
  b: true
  d: true
  e: true
  electron: true
  esbuild: true
  i: true
  l: true
  s: true
  u: true
